"""empty message

Revision ID: 048e7deb256c
Revises: a351e14e44a6
Create Date: 2018-05-04 16:49:35.836764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048e7deb256c'
down_revision = 'a351e14e44a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'is_delete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('is_delete', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
