"""empty message

Revision ID: effb6759bb88
Revises: 
Create Date: 2018-04-28 10:03:12.958441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'effb6759bb88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('id_card', sa.String(length=64), nullable=True),
    sa.Column('race', sa.String(length=64), nullable=True),
    sa.Column('origin', sa.String(length=64), nullable=True),
    sa.Column('tel', sa.String(length=64), nullable=True),
    sa.Column('course', sa.String(length=64), nullable=True),
    sa.Column('is_header_teacher', sa.Boolean(), nullable=True),
    sa.Column('working_date', sa.Date(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('change_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachers_id_card'), 'teachers', ['id_card'], unique=True)
    op.create_index(op.f('ix_teachers_name'), 'teachers', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teachers_name'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_id_card'), table_name='teachers')
    op.drop_table('teachers')
    # ### end Alembic commands ###
